apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
      - name: log-output
        image: dawidl022/simple-logger@sha256:ca6fb06f9cec0246b6863141f9b21ae8be3fe41def44b941551a732ac934bdc3
