apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
spec:
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: dawidl022/simple-logger:sha-2a0cd06
          env:
            - name: PORT
              value: "8081"
          envFrom:
            - configMapRef:
                name: log-dotenv
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 8081
