kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dummy-site-controller
rules:
  - apiGroups: [""]
    resources: ["services", "configmaps"]
    verbs: ["get", "create", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "create", "update"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "create", "update"]
