apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-site-controller
spec:
  selector:
    matchLabels:
      app: dummy-site-controller
  template:
    metadata:
      labels:
        app: dummy-site-controller
    spec:
      serviceAccountName: dummy-site-controller
      containers:
        - name: dummy-site-controller
          image: dawidl022/dummy-site-controller:0.1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
