apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: exercises
spec:
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: ping-pong
          image: dawidl022/ping-pong:sha-4ec2d17
          volumeMounts:
            - mountPath: /stats
              name: shared-volume
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-env
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-env
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-env
                  key: POSTGRES_PASSWORD
            - name: DB_URL
              value: 'postgresql://$(DB_USER):$(DB_PASSWORD)@postgres-pong-svc:5432/$(DB_NAME)?sslmode=disable'
