apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster
  namespace: project
spec:
  replicas: 6
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      labels:
        app: todo-broadcaster
    spec:
      containers:
        - name: todo-broadcaster
          image: dawidl022/todo-broadcaster:sha-d9fa869
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          env:
            - name: SEND_MESSAGE_URL
              valueFrom:
                secretKeyRef:
                  name: broadcaster-secrets
                  key: SEND_MESSAGE_URL
            - name: CHAT_ID
              valueFrom:
                secretKeyRef:
                  name: broadcaster-secrets
                  key: CHAT_ID
            - name: SEND_MESSAGE_TEMPLATE
              value: '{"chat_id": $(CHAT_ID), "text": {{ .Message }}}'
            - name: NATS_URL
              value: nats://my-nats:4222
