apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-broadcaster
  namespace: project
spec:
  replicas: 6
  selector:
    matchLabels:
      app: todo-broadcaster
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: todo-broadcaster
    spec:
      containers:
        - env:
            - name: SEND_MESSAGE_URL
              valueFrom:
                secretKeyRef:
                  key: SEND_MESSAGE_URL
                  name: broadcaster-secrets
            - name: CHAT_ID
              valueFrom:
                secretKeyRef:
                  key: CHAT_ID
                  name: broadcaster-secrets
            - name: SEND_MESSAGE_TEMPLATE
              value: '{"chat_id": $(CHAT_ID), "text": {{ .Message }}}'
            - name: NATS_URL
              value: nats://my-nats:4222
          image: PROJECT/IMAGE_BROADCASTER
          name: todo-broadcaster
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
