apiVersion: v1
kind: Secret
metadata:
    name: broadcaster-secrets
    namespace: project
type: Opaque
data:
    SEND_MESSAGE_URL: ENC[AES256_GCM,data:6nSvsSigNAaaAMGe52Q2ENyDLMZzvcFCID06T8IeqjC2JyoCte2xwAY5YpLaySGSoJ/fn9CC2JWefo9COwuAwSyb9LI9uyRZH8j5b5rd99RXVfWASv8lAJu4S2lHuj+mJERK1gm4x4VYYedrcBDMm1XDXD4=,iv:zFRaiweiabLKC/or0Xkn2rgpkTvITL0aqiLD3drJFuU=,tag:Fc/78WimbB4sChlBOg52rQ==,type:str]
    CHAT_ID: ENC[AES256_GCM,data:zKE1XNVOX4xeRtme5TsLIA==,iv:O4caQs6WqWpr00QVx4XxW2FSwutNVSRhlS1SHmACopo=,tag:IeZN5C2pImv34OE5bXKlXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kmamjr63s5gyvnjnwmy4j8n03gnme2wksuuajfm6t43de0nezdmsl3lcvp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBua05MaWhlM0U5OE9BTzNh
            Q1NwN0xJVHNvL0ZDWkZFWXZjRnArakhzUnljCmx4WmluOVBXKzI4Uk0yRGRKZXV2
            MXdnOG41WXB4ZlF5MnVLVnRFT01HeWsKLS0tIE0vT0xRMDRhRmY2SGNXY1hMOTVF
            UjIyNXgyUmtxYWVWZXltRUp0OVp3UDQKANdbxW6USSJwnCEgAWr6HZzQ5GB8oPeN
            s98ja4RfvVMFrEr6XntGZbsCaKodtks/eGvhMVO/bJ2XZ2I+4M4h2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-07T11:43:21Z"
    mac: ENC[AES256_GCM,data:mPt12vkMTpv9dQv1iMIh+2ip5lFXPGm+wkOWFh8ukPL0Fyw547rwDNpx6kAxWbrkyZBTbejxbPTRHeBRvJMCyzZW4VTlzMp1r1dlcetifXf+7kSrvXHbHJsB6ahDmZBUp/evQXkCexjeCcbPgqyU0WlTlr/223i5tCboP0iEnW8=,iv:4RX3dWKXF+n4aqgie/izpzLnS1fUjjoKJrtr8G4WXtI=,tag:gfwqgegs2nmKwQy7QEFWdg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
