apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui
  namespace: project
spec:
  selector:
    matchLabels:
      app: todo-ui
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: todo-ui
    spec:
      containers:
        - image: PROJECT/IMAGE_UI
          name: todo-ui
