apiVersion: v1
kind: Service
metadata:
  name: todo-ui-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todo-ui
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP
