apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage
spec:
  metrics:
    - name: cpu-usage
      initialDelay: 30s
      successCondition: result < 0.1
      provider:
        prometheus:
          address: http://kube-prometheus-stack-1659-prometheus.prometheus.svc.cluster.local:9090
          query: scalar(sum(rate(container_cpu_usage_seconds_total{namespace="project"}[2m])))
