apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  namespace: project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: todo-api
    spec:
      containers:
        - env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: database-env
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: database-env
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: database-env
            - name: DB_URL
              value: postgresql://$(DB_USER):$(DB_PASSWORD)@database-svc:5432/$(DB_NAME)?sslmode=disable
            - name: NATS_URL
              value: nats://my-nats:4222
          image: PROJECT/IMAGE_API
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
          name: todo-api
          readinessProbe:
            httpGet:
              path: healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - mountPath: /cache
              name: cache-volume
      volumes:
        - emptyDir: {}
          name: cache-volume
