apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  namespace: project
spec:
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      volumes:
        - name: cache-volume
          emptyDir: {}
      containers:
        - name: todo-api
          image: dawidl022/todo-app:sha-0a0242f
          volumeMounts:
            - mountPath: /cache
              name: cache-volume
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: database-env
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-env
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-env
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: database-env
                  key: POSTGRES_HOST
