apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: dawidl022/todo-app@sha256:167d46c85cd2f8cd6da53325fc3ddaed62095d14694e9a8c49479f5bb4800846
