apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-app-ingress
  namespace: project
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: todo-ui-svc
            port:
              number: 80
      - pathType: Prefix
        path: /api
        backend:
          service:
            name: todo-api-svc
            port: 
              number: 8080
