apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
images:
- name: PROJECT/IMAGE_API
  newName: dawidl022/todo-api
  newTag: 82c9d195dafbb343351f8dcafcedff2c52cb52dc
- name: PROJECT/IMAGE_BROADCASTER
  newName: dawidl022/todo-broadcaster
  newTag: 82c9d195dafbb343351f8dcafcedff2c52cb52dc
- name: PROJECT/IMAGE_UI
  newName: dawidl022/todo-ui
  newTag: 82c9d195dafbb343351f8dcafcedff2c52cb52dc
resources:
- manifests/ingress.yml
- backend/manifests/db/database.yml
- backend/manifests/analysistemplate.yml
- backend/manifests/rollout.yml
- backend/manifests/service.yml
- services/broadcaster/manifests/deployment.yml
- frontend/manifests/deployment.yml
- frontend/manifests/service.yml
