apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
images:
  - name: PROJECT/IMAGE_API
  - name: PROJECT/IMAGE_UI
  - name: PROJECT/IMAGE_BROADCASTER
resources:
  - manifests/ingress.yml
  - backend/manifests/db/database.yml
  - backend/manifests/analysistemplate.yml
  - backend/manifests/rollout.yml
  - backend/manifests/service.yml
  - services/broadcaster/manifests/deployment.yml
  - frontend/manifests/deployment.yml
  - frontend/manifests/service.yml
