apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
images:
- name: PROJECT/IMAGE_API
  newName: dawidl022/todo-api
  newTag: 575f4a76ec600a3370dc21b4b1a89478973df309
- name: PROJECT/IMAGE_BROADCASTER
  newName: dawidl022/todo-broadcaster
  newTag: 575f4a76ec600a3370dc21b4b1a89478973df309
- name: PROJECT/IMAGE_UI
  newName: dawidl022/todo-ui
  newTag: 575f4a76ec600a3370dc21b4b1a89478973df309
resources:
- manifests/ingress.yml
- backend/manifests/db/database.yml
- backend/manifests/deployment.yml
- backend/manifests/service.yml
- backend/manifests/secrets/secrets.enc.yml
- services/broadcaster/manifests/deployment.yml
- services/broadcaster/manifests/secrets.enc.yml
- frontend/manifests/deployment.yml
- frontend/manifests/service.yml
