apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
images:
- name: PROJECT/IMAGE_API
  newName: dawidl022/todo-api
  newTag: 3e057c25ef5cba0a9053cbe204c2e2b7e083b1f7
- name: PROJECT/IMAGE_BROADCASTER
  newName: dawidl022/todo-broadcaster
  newTag: 3e057c25ef5cba0a9053cbe204c2e2b7e083b1f7
- name: PROJECT/IMAGE_UI
  newName: dawidl022/todo-ui
  newTag: 3e057c25ef5cba0a9053cbe204c2e2b7e083b1f7
resources:
- manifests/ingress.yml
- backend/manifests/db/database.yml
- backend/manifests/deployment.yml
- backend/manifests/service.yml
- backend/manifests/secrets/secrets.enc.yml
- services/broadcaster/manifests/deployment.yml
- services/broadcaster/manifests/secrets.enc.yml
- frontend/manifests/deployment.yml
- frontend/manifests/service.yml
