apiVersion: v1
kind: Secret
metadata:
    name: database-env
    namespace: project
type: Opaque
data:
    POSTGRES_DB: ENC[AES256_GCM,data:lYNBvpXzUpE=,iv:ILLykzY2PLYbVEfr/NfoMdPWYp7BKpXcIZ+1lQLrsXU=,tag:y23eFZTLgpqGqr7UyL4CxQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:2mfUJJMTwI8=,iv:sSr+wcnB8ukFRfJy5ri1t+PILWEh4EznfYwWv333u7I=,tag:/CAyB9D6YY+39hOt/pCAAQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:iPSA33ha36coY+f2,iv:WEdpgKjJjiP6tnCHq1OtrK8f2nzZoVI52xnZkbf6w10=,tag:eX0kcPsa2XqmQwJXp1nkLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kmamjr63s5gyvnjnwmy4j8n03gnme2wksuuajfm6t43de0nezdmsl3lcvp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhc0c3VzBwbndRNUxiS2d5
            TGQ5Z3p0WlJIMXpDaXIrZ3E1TlpMdlJWc0NjCm1abExtSUJWMEVCSXBJeml6eXRW
            N1VRbkp6cXhrc3ZFcENVUlkzM1A5ckUKLS0tIEVVOXJKRDFObHRjM0hnV3NTTXZu
            SThZZ3dCanlzNTl2dU1CV3dZS1QxNjQKM6tROyATHkS3t7MD5tZwMTTqH8Ie0rPP
            uJgK3xi0vRspIrvSaCVhZMQxdiO7nc3WhQf/jnpAEHb4wFDcLm1iQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-29T20:09:40Z"
    mac: ENC[AES256_GCM,data:P3Ykr3UwnbuVLsPWeo/agAvmJKJhxQWnYwmdO15X7QbeU3h7glrm9Q2noaMffhc3BVm4yRYR/wg4Gjbg4MuoiPlo9P8zWz1Mg3ffDwPS2ASuxO0FrWSK7lLq/PVN0WB+O07GMjVZuc+k/1mqUWHf4GfyN7Oxj/lh/4diCKzKRXg=,iv:cG4wKD/IXLqyyQnr+q2GGnhJH9VcNLLq5FNP+qh9v2M=,tag:IBOjcjoctqTYzZhJQ4pRSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
