name: Push Logger image to DockerHub

on:
  push:
    paths:
      - log-output/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build log-output -t dawidl022/simple-logger:$(date +%s)
      - name: Push to DockerHub
        run: docker push dawidl022/simple-logger
