on:
  push:
    paths:
      - todo/**
      - "!todo/manifests"

jobs:
  push_todo_app_to_registry:
    uses: ./.github/workflows/docker.yml
    with:
      dockerfile_path: todo
      image_name: dawidl022/todo-app
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
