name: Push todo-app image to DockerHub

on:
  push:
    paths:
      - todo/backend/**
      - '!todo/manifests/**'

jobs:
  push_todo_app_to_registry:
    uses: ./.github/workflows/docker.yml
    with:
      dockerfile_path: todo/backend
      image_name: dawidl022/todo-app
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
