name: Release todo app to GitOps

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/todo-gitops.yml
      - todo/**

env:
  IMAGE_API: dawidl022/todo-api
  IMAGE_UI: dawidl022/todo-ui
  IMAGE_BROADCASTER: dawidl022/todo-broadcaster

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push backend
        uses: docker/build-push-action@v2
        with:
          context: todo/backend
          push: true
          tags: $IMAGE_API:${{ github.sha }}

      - name: Build and Push frontend
        uses: docker/build-push-action@v2
        with:
          context: todo/frontend
          push: true
          tags: $IMAGE_UI:${{ github.sha }}

      - name: Build and push broadcaster
        uses: docker/build-push-action@v2
        with:
          context: todo/services/broadcaster
          push: true
          tags: $IMAGE_BROADCASTER:${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Update yamls
        working-directory: todo
        run: |-
          kustomize edit set image PROJECT/IMAGE_API=$IMAGE_API:${{ github.sha }}
          kustomize edit set image PROJECT/IMAGE_UI=$IMAGE_UI:${{ github.sha }}
          kustomize edit set image PROJECT/IMAGE_BROADCASTER=$IMAGE_BROADCASTER:${{ github.sha }}

      - name: Commit and push
        uses: EndBug/add-and-commit@v7
        with:
          add: todo/kustomization.yaml
          message: New version release for gitops-todo ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
