name: Push todo-app api image to DockerHub

on:
  push:
    paths:
      - todo/backend/**
      - "!todo/backend/manifests/**"

jobs:
  push_todo_api_to_registry:
    uses: ./.github/workflows/docker.yml
    with:
      dockerfile_path: todo/backend
      image_name: dawidl022/todo-app
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
