apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-ui
spec:
  selector:
    matchLabels:
      app: todo-ui
  template:
    metadata:
      labels:
        app: todo-ui
    spec:
      containers:
        - name: todo-ui
          image: PROJECT/IMAGE_UI
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
